# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
