# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0003_auto_20180924_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
